#!/usr/bin/env python3
"""
adsentice_warp_ingest_max.py — M2 PREMIUM: Registry Semantico MAX
═══════════════════════════════════════════════════════════════════
Fontes combinadas:
  1. shadcn/ui v4 (context7 + source code) — 30+ components
  2. Radix Primitives (context7 + WAI-ARIA docs) — 25+ primitives
  3. 21st-magic (77 visual components) — animacoes, efeitos, mockups

Cada componente embedado com:
  embedding = vec(description + intent + triggers)
  payload   = { kind, tag, name, description, intent, triggers,
                category, mode, edges, tokens, surfaces, segments,
                a11y_role, a11y_keyboard, a11y_contrast,
                source_name, source_type, source_quality }

medido=verdade · ADR-0018 + ADR-0020 · 2026-07-14
"""

import json, os, time, uuid
from urllib.request import Request, urlopen

EMBED_URL = "http://127.0.0.1:8081/embed"
QDRANT_URL = "http://127.0.0.1:6352"
COLLECTION = "adsentice-self"
TAG = "adsentice-warp"
ALL_SEGMENTS = ["saude", "beleza", "servicos", "alimentacao", "comercio", "educacao", "hospitalidade"]

def embed(texts: list[str]) -> list[list[float]]:
    texts = [t[:800] for t in texts]
    req = Request(EMBED_URL, data=json.dumps({"texts": texts}).encode(),
                  headers={"Content-Type": "application/json"})
    return json.loads(urlopen(req, timeout=30).read())["vectors"]

def upsert(points: list[dict]) -> str:
    body = json.dumps({"points": points}).encode()
    req = Request(f"{QDRANT_URL}/collections/{COLLECTION}/points?wait=true",
                  data=body, headers={"Content-Type": "application/json"}, method="PUT")
    return json.loads(urlopen(req, timeout=30).read()).get("status", "error")

def mk_payload(c: dict) -> dict:
    return {
        "id": c["id"],
        "kind": "component",
        "tag": TAG,
        "name": c["name"],
        "description": c["description"],
        "intent": c["intent"],
        "category": c["category"],
        "type": c.get("type", "atom"),
        "mode": c.get("mode", "design-system"),
        "triggers": c.get("triggers", []),
        "edges": c.get("edges", []),
        "tokens": c.get("tokens", []),
        "surfaces": c.get("surfaces", []),
        "segments": c.get("segments", ALL_SEGMENTS),
        "source_name": c.get("source_name", "unknown"),
        "source_type": c.get("source_type", "component"),
        "source_quality": c.get("source_quality", "P1"),
        "a11y_role": c.get("a11y_role", "generic"),
        "a11y_keyboard": c.get("a11y_keyboard", False),
        "a11y_contrast": c.get("a11y_contrast", 4.5),
        "ts": int(time.time()),
    }

# ═══════════════════════════════════════════════════════════════
# CATEGORIA 1: SHADCN/UI CORE (actions, data-display, forms)
# Fonte: context7 shadcn/ui source code + docs
# ═══════════════════════════════════════════════════════════════

SHADCN_CORE = [
    # ── Actions ──
    {
        "id": "button", "type": "atom", "name": "Button",
        "description": "Elemento clicavel. Variants: default, destructive, outline, secondary, ghost, link. Sizes: xs, sm, default, lg, icon. Slot para asChild pattern. Focus-visible ring com contraste 4.5+. Suporta aria-invalid para formularios.",
        "intent": "acionar acao primaria, confirmar, submeter formulario, navegar, deletar, toggle",
        "category": "action",
        "triggers": ["botao", "button", "click", "acao", "confirmar", "enviar", "submit", "deletar", "cancelar", "cta", "call to action", "comprar", "assinar", "salvar", "baixar", "exportar"],
        "mode": "design-system", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow"],
        "surfaces": ["S1", "S4", "S6", "S9", "S10", "S11", "S14"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "toggle", "type": "molecule", "name": "Toggle",
        "description": "Bootstrap Toggle is a jQuery plugin/widget that converts plain checkboxes into responsive toggle switch buttons. Built for Bootstrap 4/5. Alternative: use Radix Toggle primitive for React.",
        "intent": "ativar ou desativar estado binario, modo escuro, notificacoes, filtro on-off",
        "category": "action",
        "triggers": ["toggle", "switch", "alternar", "ligar", "desligar", "ativar", "desativar", "chave", "interruptor"],
        "mode": "design-system", "edges": [],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S3", "S9", "S10", "S16"], "segments": ALL_SEGMENTS,
        "source_name": "shadcn/ui v4 (Switch)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "switch", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "toggle-group", "type": "organism", "name": "Toggle Group",
        "description": "Grupo de botoes toggle mutuamente exclusivos ou multi-select. Tipo barra de ferramentas compacta. Acessivel via teclado com setas e Tab.",
        "intent": "selecionar opcao entre conjunto, toolbar, alinhamento texto, filtro multiple-choice",
        "category": "action",
        "triggers": ["toggle group", "grupo de alternancia", "toolbar", "barra de ferramentas", "alinhamento"],
        "mode": "dashboard", "edges": ["toggle"],
        "tokens": ["color", "spacing", "radius"],
        "surfaces": ["S3", "S16"], "segments": ALL_SEGMENTS,
        "source_name": "Radix UI ToggleGroup", "source_type": "pattern", "source_quality": "P0",
        "a11y_role": "toolbar", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Data Display ──
    {
        "id": "card",
        "type": "molecule", "name": "Card",
        "description": "Container flexivel com 7 sub-componentes: Card, CardHeader, CardTitle, CardDescription, CardAction, CardContent, CardFooter. Suporta @container queries para layouts responsivos dentro de cards.",
        "intent": "exibir informacao agrupada, destacar conteudo, organizar dashboard, mostrar metrica KPI, resumo de lead",
        "category": "data-display",
        "triggers": ["card", "cartao", "container", "bloco", "painel", "card de metrica", "kpi card", "stat card", "resumo", "destaque", "widget"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow"],
        "surfaces": ["S3", "S9", "S10", "S11", "S15", "S16", "S17", "S18"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "table",
        "type": "organism", "name": "Table",
        "description": "Tabela de dados com Table, TableHeader, TableBody, TableRow, TableHead, TableCell, TableFooter, TableCaption. Suporta DataTable com sorting, filtering, pagination via @tanstack/react-table.",
        "intent": "exibir dados tabulares, listar leads, mostrar ranking, comparar metricas, exportar dados",
        "category": "data-display",
        "triggers": ["tabela", "table", "lista", "dados", "grid", "planilha", "ranking", "leads", "metricas", "comparacao", "exportar", "csv"],
        "mode": "dashboard", "edges": ["button", "select", "input"],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S3", "S9", "S10", "S15", "S16"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "table", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "badge",
        "type": "atom", "name": "Badge",
        "description": "Indicador visual compacto para status, contagem, tags. Variants: default, secondary, destructive, outline. Usado para labels de categoria, status de lead, planos.",
        "intent": "indicar status, mostrar contagem, etiquetar categoria, destacar nivel, mostrar plano",
        "category": "data-display",
        "triggers": ["badge", "emblema", "tag", "etiqueta", "status", "contagem", "selo", "indicador", "nivel", "plano"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S3", "S9", "S10", "S15", "S16"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "status", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "avatar",
        "type": "molecule", "name": "Avatar",
        "description": "Foto de perfil do usuario com 6 sub-componentes: Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup, AvatarGroupCount. Sizes: sm, default, lg. Fallback mostra iniciais quando imagem falha.",
        "intent": "exibir foto de perfil, representar usuario, mostrar grupo de pessoas, indicar presenca",
        "category": "data-display",
        "triggers": ["avatar", "foto", "perfil", "usuario", "iniciais", "grupo", "pessoas", "presenca"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "spacing", "radius"],
        "surfaces": ["S3", "S9", "S19"],
        "source_name": "shadcn/ui v4 (Radix)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "img", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "chart",
        "type": "organism", "name": "Chart",
        "description": "Sistema de graficos: ChartContainer, ChartConfig, ChartTooltip, ChartTooltipContent. BarChart, LineChart, AreaChart, PieChart, RadarChart via Recharts. Config por tema com variaveis CSS. Interactive com estado.",
        "intent": "visualizar dados, grafico de barras, linha do tempo, pizza, radar, dashboard analytics",
        "category": "data-display",
        "triggers": ["grafico", "chart", "barras", "linha", "pizza", "radar", "area", "dashboard", "analytics", "visualizacao", "metrica visual"],
        "mode": "dashboard", "edges": ["card"],
        "tokens": ["color", "spacing", "radius", "typography"],
        "surfaces": ["S3", "S9", "S15", "S16", "S17"],
        "source_name": "shadcn/ui v4 (Recharts)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "img", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "skeleton",
        "type": "atom", "name": "Skeleton",
        "description": "Placeholder animado (pulse) para estados de carregamento. Previne layout shift (CLS). Formato: linhas, circulos, retangulos, cards. Acessivel: aria-busy=true ate dados carregarem.",
        "intent": "indicar carregamento, evitar layout shift, mostrar que conteudo esta sendo buscado",
        "category": "feedback",
        "triggers": ["skeleton", "esqueleto", "loading", "carregando", "placeholder", "shimmer", "pulse", "aguarde"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "radius", "animation"],
        "surfaces": ["S3", "S9", "S10", "S15", "S16"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "status", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },

    # ── Navigation ──
    {
        "id": "breadcrumb",
        "type": "molecule", "name": "Breadcrumb",
        "description": "Trilha de navegacao hierarquica. Lista de links com separadores automaticos. Acessivel: nav com aria-label='Breadcrumb', ol+li estruturado. Ultimo item aria-current=page.",
        "intent": "mostrar localizacao hierarquica, navegar para niveis superiores, orientar usuario",
        "category": "navigation",
        "triggers": ["breadcrumb", "migalha", "trilha", "hierarquia", "localizacao", "path", "caminho"],
        "mode": "dashboard", "edges": [],
        "tokens": ["typography", "color", "spacing"],
        "surfaces": ["S3", "S9"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "navigation", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "pagination",
        "type": "molecule", "name": "Pagination",
        "description": "Navegacao entre paginas de dados. Botoes: first, prev, numeros, next, last. Info de pagina atual/total. Acessivel via aria-label em cada botao.",
        "intent": "navegar entre paginas de resultados, controlar fluxo de dados, ir para pagina especifica",
        "category": "navigation",
        "triggers": ["paginacao", "paginas", "next", "prev", "anterior", "proximo", "primeira", "ultima", "navegacao de pagina"],
        "mode": "dashboard", "edges": ["button"],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S3", "S9", "S10", "S15"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "navigation", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Overlays ──
    {
        "id": "dialog",
        "type": "molecule", "name": "Dialog (Modal)",
        "description": "Janela modal com overlay. Foco aprisionado (trap). Esc fecha. Titulo + descricao para screen readers. Animacao de entrada/saida. 5 sub-componentes: Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter.",
        "intent": "confirmar acao destrutiva, exibir formulario em modal, mostrar detalhes sem sair da pagina, alerta critico",
        "category": "feedback",
        "triggers": ["modal", "dialog", "popup", "confirmacao", "alerta", "janela", "confirmar exclusao", "detalhes", "termos", "aviso"],
        "mode": "dashboard", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "shadow", "animation", "z-index"],
        "surfaces": ["S3", "S9", "S14", "S18"],
        "source_name": "shadcn/ui v4 (Radix Dialog)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "alert-dialog",
        "type": "molecule", "name": "Alert Dialog",
        "description": "Modal para confirmacoes criticas. Interrompe o fluxo do usuario. Titulo + descricao + botoes de acao/cancel. Foco no botao menos destrutivo. Essencial para acoes irreversiveis.",
        "intent": "confirmar acao irreversivel, alertar sobre consequencia grave, prevenir erro do usuario",
        "category": "feedback",
        "triggers": ["alerta", "confirmacao", "certeza", "irreversivel", "excluir conta", "deletar tudo", "tem certeza", "warning"],
        "mode": "dashboard", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S3", "S9", "S14"],
        "source_name": "shadcn/ui v4 (Radix AlertDialog)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "alertdialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "sheet",
        "type": "organism", "name": "Sheet (Painel Lateral)",
        "description": "Painel que desliza da borda. Top, right, bottom, left. Swipe fecha no mobile. Sobrepoe conteudo principal. Ideal para navegacao mobile, filtros, carrinho, detalhes.",
        "intent": "exibir painel lateral, navegacao mobile, filtros avancados, detalhes do item, carrinho, configuracoes",
        "category": "navigation",
        "triggers": ["sheet", "painel", "lateral", "drawer", "slide", "filtro lateral", "menu mobile", "detalhes", "carrinho"],
        "mode": "dashboard", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "shadow", "animation", "z-index"],
        "surfaces": ["S3", "S9", "S16"],
        "source_name": "shadcn/ui v4 (Radix Dialog)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "tooltip",
        "type": "atom", "name": "Tooltip",
        "description": "Dica contextual ao passar mouse/foco. Delay 700ms default. Nao deve conter informacao essencial (inacessivel no touch). Side: top, bottom, left, right. Alinhamento inteligente.",
        "intent": "explicar funcionalidade, mostrar atalho de teclado, dar contexto adicional sem poluir a interface",
        "category": "feedback",
        "triggers": ["tooltip", "dica", "hover", "tooltip", "contexto", "explicacao rapida", "atalho"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S3", "S9", "S14"],
        "source_name": "shadcn/ui v4 (Radix Tooltip)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "tooltip", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "hover-card",
        "type": "molecule", "name": "Hover Card",
        "description": "Card de preview que aparece ao passar mouse. Mais rico que tooltip — suporta imagens, links, botoes. Ideal para preview de perfil, produto, lead. Fecha ao mover mouse para fora.",
        "intent": "preview de perfil, preview de produto, cartao de informacao rica ao hover, detalhes do lead",
        "category": "feedback",
        "triggers": ["hover card", "preview", "hover", "cartao flutuante", "detalhes rapidos", "perfil rapido"],
        "mode": "dashboard", "edges": ["card"],
        "tokens": ["color", "spacing", "radius", "shadow", "z-index", "animation"],
        "surfaces": ["S3", "S9", "S10"],
        "source_name": "shadcn/ui v4 (Radix HoverCard)", "source_type": "component", "source_quality": "P1",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "popover",
        "type": "molecule", "name": "Popover",
        "description": "Conteudo flutuante ancorado a um trigger. Similar a tooltip mas persistente — clica para abrir/fechar. Suporta botoes, inputs, listas. Ideal para seletor de cor, filtro rapido, mini-form.",
        "intent": "exibir conteudo contextual rico, seletor de cor, filtro rapido, mini-formulario, picker",
        "category": "feedback",
        "triggers": ["popover", "flutuante", "ancorado", "popup", "seletor", "picker", "mini-form"],
        "mode": "dashboard", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S3", "S9", "S16"],
        "source_name": "shadcn/ui v4 (Radix Popover)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Forms ──
    {
        "id": "form",
        "type": "organism", "name": "Form",
        "description": "Formulario com validacao via react-hook-form + zod. Sub-componentes: Form, FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage. Erro com aria-invalid + mensagem descritiva.",
        "intent": "coletar dados do usuario, validar entrada, submeter formulario, cadastro, login, onboarding",
        "category": "form",
        "triggers": ["formulario", "form", "cadastro", "login", "input", "campos", "validacao", "dados", "registro", "contato", "onboarding"],
        "mode": "dashboard", "edges": ["input", "label", "button"],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S4", "S6", "S14"],
        "source_name": "shadcn/ui v4 + react-hook-form + zod", "source_type": "pattern", "source_quality": "P0",
        "a11y_role": "form", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "input",
        "type": "atom", "name": "Input",
        "description": "Campo de entrada de texto. Types: text, email, password, number, tel, url, search. States: default, focus, disabled, error (aria-invalid), readonly. Placeholder acessivel. Label requerido via htmlFor.",
        "intent": "coletar texto, email, senha, busca, filtro, pesquisa, numero, telefone, url",
        "category": "form",
        "triggers": ["input", "campo", "texto", "entrada", "escrever", "digitar", "busca", "pesquisa", "email", "senha", "telefone", "url"],
        "mode": "design-system", "edges": ["label"],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S3", "S4", "S6", "S9", "S14"],
        "source_name": "shadcn/ui v4 (Base UI)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "textbox", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "textarea",
        "type": "atom", "name": "Textarea",
        "description": "Campo de texto multi-linha. Resize: none, vertical, horizontal, both. Rows e maxRows. Ideal para descricao, bio, mensagem, feedback. Mesmo styling do Input.",
        "intent": "coletar texto longo, descricao, bio, mensagem, feedback, comentario, observacao",
        "category": "form",
        "triggers": ["textarea", "area de texto", "texto longo", "descricao", "bio", "mensagem", "feedback", "comentario", "observacao", "multi-linha"],
        "mode": "design-system", "edges": ["label"],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S3", "S4", "S6", "S9", "S14"],
        "source_name": "shadcn/ui v4", "source_type": "component", "source_quality": "P0",
        "a11y_role": "textbox", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "select",
        "type": "molecule", "name": "Select",
        "description": "Dropdown de selecao unica com Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectLabel, SelectItem, SelectSeparator. Busca integrada (typeahead). Navegacao por teclado: setas + Enter + Esc.",
        "intent": "selecionar opcao entre varias, escolher categoria, filtrar por tipo, selecionar plano, escolher segmento",
        "category": "form",
        "triggers": ["select", "selecao", "dropdown", "escolher", "opcao", "categoria", "filtro", "combo", "combobox", "menu de opcoes"],
        "mode": "dashboard", "edges": ["label"],
        "tokens": ["color", "typography", "spacing", "radius", "z-index"],
        "surfaces": ["S3", "S9", "S15", "S16"],
        "source_name": "shadcn/ui v4 (Radix Select)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "combobox", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "combobox",
        "type": "molecule", "name": "Combobox",
        "description": "Select com busca textual. Filtra opcoes conforme digita. Command+Popover pattern: tecla para abrir, digita para filtrar, Enter para selecionar. Ideal para listas longas (cidades, categorias, clientes).",
        "intent": "buscar e selecionar em lista longa, autocomplete, pesquisa com selecao, typeahead search",
        "category": "form",
        "triggers": ["combobox", "autocomplete", "busca com selecao", "typeahead", "pesquisa dropdown", "search select"],
        "mode": "dashboard", "edges": ["input", "select", "popover"],
        "tokens": ["color", "typography", "spacing", "radius", "z-index"],
        "surfaces": ["S3", "S9", "S15"],
        "source_name": "shadcn/ui v4", "source_type": "pattern", "source_quality": "P0",
        "a11y_role": "combobox", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "checkbox",
        "type": "atom", "name": "Checkbox",
        "description": "Caixa de selecao binaria. States: unchecked, checked, indeterminate. Acessivel: role=checkbox, Space para toggle, aria-checked. Com label clicavel. Ideal para listas de selecao multipla, termos.",
        "intent": "selecionar multiplas opcoes, confirmar termo, marcar item, toggle lista, selecao multipla",
        "category": "form",
        "triggers": ["checkbox", "caixa de selecao", "check", "marcar", "selecionar multiplo", "termos", "concordo", "selecionar varios"],
        "mode": "design-system", "edges": ["label"],
        "tokens": ["color", "spacing", "radius"],
        "surfaces": ["S3", "S4", "S6", "S9", "S14", "S16"],
        "source_name": "shadcn/ui v4 (Radix Checkbox)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "checkbox", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "radio-group",
        "type": "molecule", "name": "Radio Group",
        "description": "Grupo de opcoes mutuamente exclusivas. Acessivel: role=radiogroup, setas navegam entre opcoes, Tab sai do grupo. Ideal para escolha unica: plano, metodo de pagamento, genero.",
        "intent": "escolher uma opcao exclusiva, selecionar plano, metodo de pagamento, preferencia unica",
        "category": "form",
        "triggers": ["radio", "radio group", "opcao exclusiva", "escolha unica", "selecao unica", "plano", "metodo"],
        "mode": "dashboard", "edges": ["label"],
        "tokens": ["color", "spacing", "radius"],
        "surfaces": ["S4", "S6", "S14"],
        "source_name": "shadcn/ui v4 (Radix RadioGroup)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "radiogroup", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "slider",
        "type": "atom", "name": "Slider",
        "description": "Controle deslizante para valor numerico em intervalo. Range min-max. Step config. Acessivel: role=slider, setas ajustam valor, Home/End vao para extremos. Ideal para preco, nota, orcamento.",
        "intent": "ajustar valor em intervalo, selecionar faixa de preco, nota, orcamento, range slider",
        "category": "form",
        "triggers": ["slider", "deslizante", "range", "faixa", "intervalo", "preco", "nota", "nivel", "ajuste"],
        "mode": "dashboard", "edges": ["label"],
        "tokens": ["color", "spacing"],
        "surfaces": ["S3", "S9", "S16"],
        "source_name": "shadcn/ui v4 (Radix Slider)", "source_type": "component", "source_quality": "P1",
        "a11y_role": "slider", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "date-picker",
        "type": "organism", "name": "Date Picker",
        "description": "Seletor de data com calendario. Navegacao entre meses/anos. Range selection (data inicio + fim). Formatacao localizada. Acessivel: botoes de navegacao, dias como grid buttons, hoje destacado.",
        "intent": "selecionar data, intervalo de datas, agendamento, periodo de relatorio, filtro por data",
        "category": "form",
        "triggers": ["date picker", "calendario", "data", "agendamento", "periodo", "selecionar data", "range de data"],
        "mode": "dashboard", "edges": ["button", "input", "popover"],
        "tokens": ["color", "typography", "spacing", "radius", "shadow"],
        "surfaces": ["S3", "S9", "S16"],
        "source_name": "shadcn/ui v4 (React Day Picker)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "input-otp",
        "type": "molecule", "name": "Input OTP",
        "description": "Campo para One-Time Password. N digitos separados. Cola automatica. Navegacao por setas. Preenchimento automatico (autocomplete='one-time-code'). Ideal para login 2FA, verificacao de telefone.",
        "intent": "digitar codigo de verificacao, autenticacao 2FA, confirmar telefone, PIN, token",
        "category": "form",
        "triggers": ["otp", "codigo", "pin", "verificacao", "token", "2fa", "autenticacao", "sms code", "whatsapp code"],
        "mode": "design-system", "edges": ["label"],
        "tokens": ["color", "typography", "spacing", "radius"],
        "surfaces": ["S4", "S14"],
        "source_name": "shadcn/ui v4 (InputOTP)", "source_type": "component", "source_quality": "P1",
        "a11y_role": "textbox", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Menus ──
    {
        "id": "dropdown-menu",
        "type": "organism", "name": "Dropdown Menu",
        "description": "Menu suspenso com 16 sub-componentes: DropdownMenu, Trigger, Content, Group, Item, CheckboxItem, RadioGroup, RadioItem, Label, Separator, Shortcut, Sub, SubTrigger, SubContent. Acessivel: setas navegam, Enter seleciona, Esc fecha.",
        "intent": "exibir menu de acoes, opcoes de navegacao, acoes contextuais, menu de usuario, configuracoes, exportar",
        "category": "navigation",
        "triggers": ["menu", "dropdown", "suspenso", "opcoes", "acoes", "context menu", "menu de usuario", "configuracoes", "perfil", "exportar"],
        "mode": "dashboard", "edges": ["button"],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S3", "S9", "S15", "S16"],
        "source_name": "shadcn/ui v4 (Radix DropdownMenu)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "menu", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "context-menu",
        "type": "organism", "name": "Context Menu",
        "description": "Menu de clique direito. Sub-componentes identicos ao DropdownMenu. Aparece na posicao do cursor. Acessivel: Shift+F10 ou botao de contexto no teclado. Ideal para acoes em item de lista.",
        "intent": "menu de clique direito, acoes contextuais em item, opcoes rapidas, editar, duplicar, deletar item",
        "category": "navigation",
        "triggers": ["context menu", "clique direito", "right click", "menu contextual", "acoes em item"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S3", "S9", "S16"],
        "source_name": "shadcn/ui v4 (Radix ContextMenu)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "menu", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "menubar",
        "type": "organism", "name": "Menubar",
        "description": "Barra de menus horizontal estilo desktop. Menus aninhaveis (sub-menus). Acessivel: Alt ativa, setas navegam entre menus e itens. Ideal para aplicacao desktop-like.",
        "intent": "barra de menus principal, navegacao estilo desktop, arquivo editar exibir ajuda, menu superior",
        "category": "navigation",
        "triggers": ["menubar", "barra de menu", "menu superior", "arquivo", "editar", "ajuda", "desktop menu"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "z-index"],
        "surfaces": ["S3"],
        "source_name": "shadcn/ui v4 (Radix Menubar)", "source_type": "component", "source_quality": "P1",
        "a11y_role": "menubar", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "navigation-menu",
        "type": "organism", "name": "Navigation Menu",
        "description": "Menu de navegacao principal para websites. Diferente de Menubar (app) — sem composite focus. Suporta dropdowns com conteudo rico (cards, imagens, listas). Responsivo com collapse em mobile.",
        "intent": "navegacao principal do site, menu com sub-menus ricos, mega menu, header navigation",
        "category": "navigation",
        "triggers": ["navegacao", "menu principal", "header", "mega menu", "nav", "site menu"],
        "mode": "design-system", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S1", "S2", "S9", "S11"],
        "source_name": "shadcn/ui v4 (Radix NavigationMenu)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "navigation", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Layout ──
    {
        "id": "tabs",
        "type": "molecule", "name": "Tabs",
        "description": "Abas para alternar entre conteudos. Tabs, TabsList, TabsTrigger, TabsContent. Navegacao: setas esquerda/direita, Home/End. Acessivel: role=tablist. Indicador visual da aba ativa com transicao suave.",
        "intent": "organizar conteudo em abas, alternar entre visoes, navegar entre secoes relacionadas, filtro por categoria",
        "category": "navigation",
        "triggers": ["tabs", "abas", "tab", "painel", "secoes", "alternar", "navegacao por abas", "tab content"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "animation"],
        "surfaces": ["S3", "S9", "S10", "S14"],
        "source_name": "shadcn/ui v4 (Radix Tabs)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "tablist", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "accordion",
        "type": "molecule", "name": "Accordion",
        "description": "Secoes expansivas colapsaveis. Accordion, AccordionItem, AccordionTrigger, AccordionContent. Uma ou multiplas abertas simultaneamente. Animacao de altura com Collapsible. Acessivel: Enter/Space expande, setas navegam entre itens.",
        "intent": "exibir conteudo expansivel, FAQ, perguntas frequentes, detalhes progressivos, menu colapsavel",
        "category": "layout",
        "triggers": ["accordion", "sanfona", "expansivel", "colapsavel", "faq", "perguntas frequentes", "detalhes", "expandir"],
        "mode": "design-system", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "animation"],
        "surfaces": ["S2", "S9", "S10", "S22"],
        "source_name": "shadcn/ui v4 (Radix Accordion)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "region", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "collapsible",
        "type": "atom", "name": "Collapsible",
        "description": "Container que expande/colapsa conteudo. Primitive base para Accordion. Anima altura de 0 para auto. Trigger + Content. Acessivel: aria-expanded no trigger, aria-hidden no content.",
        "intent": "mostrar ou esconder conteudo, toggle de visibilidade, revelar mais detalhes",
        "category": "layout",
        "triggers": ["collapsible", "colapsar", "expandir", "mostrar mais", "ver mais", "toggle conteudo", "revelar"],
        "mode": "design-system", "edges": [],
        "tokens": ["animation"],
        "surfaces": ["S2", "S9", "S10", "S22"],
        "source_name": "Radix UI Collapsible", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "separator",
        "type": "atom", "name": "Separator",
        "description": "Linha divisoria horizontal ou vertical. Separa secoes, itens de menu, conteudo. Decorativo (aria-hidden=true) ou semantico (role=separator). Orientation: horizontal, vertical.",
        "intent": "separar secoes visuais, dividir conteudo, linha horizontal, divisor de menu",
        "category": "layout",
        "triggers": ["separador", "divisor", "linha", "hr", "separator", "divider"],
        "mode": "design-system", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S2", "S3", "S9", "S10", "S22"],
        "source_name": "shadcn/ui v4 (Radix Separator)", "source_type": "component", "source_quality": "P1",
        "a11y_role": "separator", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "scroll-area",
        "type": "molecule", "name": "Scroll Area",
        "description": "Container com scroll customizado. ScrollArea, ScrollBar (vertical/horizontal). Thumb com proporcao ao conteudo. Touch-friendly (native scroll no mobile). Acessivel via teclado.",
        "intent": "scroll personalizado, area com overflow, container com scroll vertical, sidebar com scroll",
        "category": "layout",
        "triggers": ["scroll", "rolagem", "overflow", "barra de rolagem", "scrollbar", "area com scroll"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "radius"],
        "surfaces": ["S3", "S9", "S16"],
        "source_name": "shadcn/ui v4 (Radix ScrollArea)", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "progress",
        "type": "atom", "name": "Progress",
        "description": "Barra de progresso. Indeterminada (animacao) ou determinada (value 0-100). Acessivel: role=progressbar, aria-valuenow, aria-valuemin, aria-valuemax. Ideal para upload, carregamento, completude de perfil, scoring.",
        "intent": "mostrar progresso, barra de carregamento, completude, scoring visual, upload progress, onboarding steps",
        "category": "feedback",
        "triggers": ["progresso", "progress", "barra", "carregamento", "upload", "completude", "scoring", "nivel", "etapas"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "radius", "animation"],
        "surfaces": ["S3", "S9", "S10", "S14"],
        "source_name": "shadcn/ui v4 (Radix Progress)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "progressbar", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "sidebar",
        "type": "organism", "name": "Sidebar",
        "description": "Navegacao lateral completa. Sidebar, SidebarContent, SidebarGroup, SidebarMenu, SidebarMenuItem, SidebarMenuButton. Collapsivel. Suporta tooltips em estado colapsado. Responsivo: drawer no mobile.",
        "intent": "navegacao lateral principal, menu admin, sidebar dashboard, gaveta de navegacao",
        "category": "layout", "mode": "dashboard",
        "triggers": ["sidebar", "navegacao lateral", "menu lateral", "side nav", "admin menu", "gaveta"],
        "edges": ["button", "tooltip", "scroll-area", "avatar"],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index", "animation"],
        "surfaces": ["S3", "S9"],
        "source_name": "shadcn/ui v4 Sidebar", "source_type": "component", "source_quality": "P0",
        "a11y_role": "navigation", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Feedback ──
    {
        "id": "toast",
        "type": "molecule", "name": "Toast (Sonner)",
        "description": "Notificacao temporaria no canto da tela. Tipos: success, error, warning, info, loading, promise. Autodismiss config. Swipe dismiss no mobile. Empilhavel (ate 3 visiveis). Acessivel: role=status, aria-live=polite.",
        "intent": "notificar usuario, mostrar confirmacao de acao, alertar erro, informar sucesso, loading state",
        "category": "feedback",
        "triggers": ["toast", "notificacao", "snackbar", "alerta", "aviso", "confirmacao", "sucesso", "erro", "mensagem temporaria"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index", "animation"],
        "surfaces": ["S3", "S9", "S14"],
        "source_name": "shadcn/ui v4 (Sonner)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "status", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "command",
        "type": "organism", "name": "Command (Paleta)",
        "description": "Paleta de comandos estilo Spotlight/CMD+K. Dialog + input busca + lista resultados. Navegacao por setas. Grupos de comandos. Shortcut display. Ideal para busca global, comandos rapidos.",
        "intent": "busca global, paleta de comandos, cmd+k, spotlight, atalhos, busca rapida, command palette",
        "category": "navigation",
        "triggers": ["command", "cmd+k", "paleta", "spotlight", "atalho", "busca global", "command palette", "quick search"],
        "mode": "dashboard", "edges": ["dialog", "input"],
        "tokens": ["color", "typography", "spacing", "radius", "shadow", "z-index"],
        "surfaces": ["S3", "S9"],
        "source_name": "shadcn/ui v4 (cmdk)", "source_type": "component", "source_quality": "P0",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
]

# ═══════════════════════════════════════════════════════════════
# CATEGORIA 2: 21st-MAGIC VISUAL COMPONENTS
# 77 componentes visuais — animacoes, efeitos, mockups
# ═══════════════════════════════════════════════════════════════

MAGIC_VISUAL = [
    # ── Text Effects ──
    {
        "id": "magic-animated-gradient-text", "type": "atom", "name": "Animated Gradient Text",
        "description": "Background gradient animado que transita entre cores para texto. Efeito sutil de gradiente em movimento. Ideal para hero headlines, landing pages.",
        "intent": "destacar titulo principal, hero text com gradiente animado, headline com efeito visual premium",
        "category": "data-display",
        "triggers": ["texto gradiente", "gradient text", "hero headline", "titulo animado", "texto colorido", "animated gradient"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "typography", "animation"],
        "surfaces": ["S1", "S11", "S2"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-animated-shiny-text", "type": "atom", "name": "Animated Shiny Text",
        "description": "Efeito de brilho (glare) que desliza sobre o texto, simulando um reflexo de luz escorrendo. Sutil e elegante.",
        "intent": "efeito premium em texto, shimmer text, texto com brilho, highlight animado",
        "category": "data-display",
        "triggers": ["texto brilhante", "shiny", "glare", "reflexo", "shimmer", "brilho no texto"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "typography", "animation"],
        "surfaces": ["S1", "S11", "S4"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-aurora-text", "type": "atom", "name": "Aurora Text",
        "description": "Efeito aurora boreal no texto. Gradientes ondulantes que lembram luzes do norte. Visual organico e hipnotico.",
        "intent": "efeito aurora em texto, headline premium, texto com gradientes organicos, visual unico",
        "category": "data-display",
        "triggers": ["aurora", "boreal", "texto aurora", "organico", "ondulante", "luzes do norte"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "typography", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-hyper-text", "type": "atom", "name": "Hyper Text",
        "description": "Animacao que embaralha letras antes de revelar o texto final. Efeito 'scramble' que resolve para o texto destino. Dinamico e chamativo.",
        "intent": "texto embaralhado, scramble effect, revelacao de texto, animacao de caracteres, efeito hacker",
        "category": "data-display",
        "triggers": ["embaralhar", "scramble", "hacker", "revelar texto", "hyper text", "letras girando"],
        "mode": "landing", "edges": [],
        "tokens": ["typography", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-morphing-text", "type": "atom", "name": "Morphing Text",
        "description": "Texto que transforma (morph) entre palavras. Transicao suave entre diferentes textos. Ideal para rotating headlines, slogans, propostas de valor.",
        "intent": "texto rotativo, morphing, palavras que mudam, rotating headline, slogan animado",
        "category": "data-display",
        "triggers": ["morph", "texto rotativo", "palavras mudando", "slogan animado", "headline rotativa"],
        "mode": "landing", "edges": [],
        "tokens": ["typography", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-typing-animation", "type": "atom", "name": "Typing Animation",
        "description": "Texto aparece como se estivesse sendo digitado. Cursor piscante no final. Velocidade configuravel. Ideal para demonstracoes, storytelling, chat UI.",
        "intent": "digitacao animada, typewriter effect, texto sendo escrito, cursor piscando, demo, storytelling",
        "category": "data-display",
        "triggers": ["digitando", "typewriter", "cursor", "escrevendo", "maquina de escrever", "typing"],
        "mode": "landing", "edges": [],
        "tokens": ["typography", "animation", "color"],
        "surfaces": ["S1", "S11", "S12"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-text-reveal", "type": "molecule", "name": "Text Reveal (Scroll)",
        "description": "Texto que aparece (fade in) conforme o usuario rola a pagina. Gatilho: elemento entra no viewport. Animacao suave de opacidade + translateY.",
        "intent": "revelar texto no scroll, fade in on scroll, animacao de entrada, scroll-triggered reveal",
        "category": "data-display",
        "triggers": ["text reveal", "scroll reveal", "aparecer no scroll", "fade in scroll", "animacao scroll"],
        "mode": "landing", "edges": [],
        "tokens": ["animation", "typography"],
        "surfaces": ["S1", "S2", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-blur-fade", "type": "molecule", "name": "Blur Fade",
        "description": "Animacao de blur + fade para entrada e saida de conteudo. Suave transicao entre estados. Ideal para transicoes de pagina, secoes.",
        "intent": "transicao blur, fade in-out suave, animacao de entrada premium, page transition",
        "category": "data-display",
        "triggers": ["blur", "desfoque", "fade", "transicao", "entrada suave", "blur fade"],
        "mode": "landing", "edges": [],
        "tokens": ["animation"],
        "surfaces": ["S1", "S2", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-spinning-text", "type": "atom", "name": "Spinning Text",
        "description": "Texto que gira em movimento circular. Velocidade, direcao e cor configuraveis. Ideal para badges circulares, selos, aros de texto.",
        "intent": "texto circular, spinning badge, selo giratorio, texto em circulo, badge rotativo",
        "category": "data-display",
        "triggers": ["spinning", "girando", "circular", "badge", "selo", "aro de texto"],
        "mode": "landing", "edges": [],
        "tokens": ["typography", "animation", "color"],
        "surfaces": ["S1", "S13"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-word-rotate", "type": "atom", "name": "Word Rotate",
        "description": "Rotacao vertical de palavras. Transicao suave entre palavras em uma frase. Ideal para 'Nos fazemos [X]' onde X rotaciona entre opcoes.",
        "intent": "rotacionar palavras, word carousel, trocar palavra na frase, emphasizar alternativas",
        "category": "data-display",
        "triggers": ["word rotate", "rotacao de palavras", "palavra girando", "word swap", "frase com alternativas"],
        "mode": "landing", "edges": [],
        "tokens": ["typography", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-sparkles-text", "type": "atom", "name": "Sparkles Text",
        "description": "Texto com particulas brilhantes (sparkles) continuas ao redor. Transicoes suaves entre sparkles. Ideal para destacar palavras especiais, precos promocionais, badges.",
        "intent": "sparkles, brilhos, estrelas, particulas no texto, destaque especial, texto magico",
        "category": "data-display",
        "triggers": ["sparkles", "brilhos", "estrelas", "particulas", "texto magico", "destaque premium"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-number-ticker", "type": "atom", "name": "Number Ticker",
        "description": "Animacao de contagem numerica. Sobe ou desce ate o numero alvo. Ideal para metricas KPI, estatisticas animadas, contadores de leads, faturamento.",
        "intent": "contador animado, numero subindo, kpi animado, metrica animada, estatistica visual",
        "category": "data-display",
        "triggers": ["contador", "numero", "ticker", "kpi animado", "metrica", "estatistica", "crescendo", "contagem"],
        "mode": "dashboard", "edges": [],
        "tokens": ["typography", "animation", "color"],
        "surfaces": ["S1", "S3", "S10", "S15"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P0",
        "a11y_role": "status", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },

    # ── Button Effects ──
    {
        "id": "magic-ripple-button", "type": "atom", "name": "Ripple Button",
        "description": "Botao com efeito ripple (ondas concentricas) ao clicar. Animacao de onda expandindo a partir do ponto de clique. Feedback visual instantaneo.",
        "intent": "botao com ripple, feedback de clique visual, ondulacao no botao, material design click",
        "category": "action",
        "triggers": ["ripple", "ondulacao", "onda", "material button", "click effect", "feedback clique"],
        "mode": "design-system", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S1", "S4", "S6", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-shimmer-button", "type": "atom", "name": "Shimmer Button",
        "description": "Botao com luz brilhante (shimmer) percorrendo sua borda. Efeito de destaque continuo. Ideal para CTA principal, botoes de compra, upgrade.",
        "intent": "botao com brilho, shimmer, destaque premium, CTA principal, botao de upgrade, comprar",
        "category": "action",
        "triggers": ["shimmer", "brilho", "borda brilhante", "cta premium", "botao upgrade", "comprar"],
        "mode": "landing", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S1", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-shiny-button", "type": "atom", "name": "Shiny Button",
        "description": "Botao com efeito shiny (brilho) que varia entre light/dark mode. Estilo dinamico com destaque visual. Parte da colecao de botoes premium.",
        "intent": "botao brilhante, shiny, premium button, destaque, modo escuro, light mode",
        "category": "action",
        "triggers": ["shiny", "brilhante", "premium", "botao com efeito", "dark mode button"],
        "mode": "landing", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S1", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-pulsating-button", "type": "atom", "name": "Pulsating Button",
        "description": "Botao com animacao de pulsacao. Chama atencao de forma sutil. Ideal para CTA principal, 'Comece Agora', 'Teste Gratis'.",
        "intent": "botao pulsante, pulse, chamar atencao, CTA, comecar agora, teste gratis",
        "category": "action",
        "triggers": ["pulsante", "pulse", "pulsar", "atencao", "cta pulsante", "chamar atencao"],
        "mode": "landing", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S1", "S4", "S6", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-rainbow-button", "type": "atom", "name": "Rainbow Button",
        "description": "Botao com efeito arco-iris animado. Cores do espectro percorrendo a borda. Maximo destaque visual. Ideal para promocoes, lancamentos.",
        "intent": "botao arco-iris, rainbow, maximo destaque, promocao, lancamento, efeito colorido",
        "category": "action",
        "triggers": ["rainbow", "arco-iris", "colorido", "maximo destaque", "promocao", "lancamento"],
        "mode": "landing", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S1", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-interactive-hover-button", "type": "atom", "name": "Interactive Hover Button",
        "description": "Botao com efeito interativo no hover. Movimento, cor, escala reagem a posicao do mouse. Sensacao de profundidade e resposta fisica.",
        "intent": "hover interativo, botao que segue mouse, efeito 3d sutil, resposta ao cursor",
        "category": "action",
        "triggers": ["hover", "interativo", "mouse", "3d", "profundidade", "cursor", "seguir mouse"],
        "mode": "landing", "edges": ["button"],
        "tokens": ["color", "spacing", "radius", "animation"],
        "surfaces": ["S1", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-cool-mode", "type": "atom", "name": "Cool Mode",
        "description": "Efeito 'cool mode' para botoes, links e outros elementos DOM. Efeito de particulas ou glow que ativa ao interagir.",
        "intent": "efeito legal em botoes, cool mode, particulas ao clicar, interacao divertida",
        "category": "action",
        "triggers": ["cool", "divertido", "particulas", "glow", "efeito especial", "interacao"],
        "mode": "landing", "edges": ["button"],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "button", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Card Effects ──
    {
        "id": "magic-magic-card", "type": "molecule", "name": "Magic Card",
        "description": "Card com efeito spotlight que segue o cursor. Borda iluminada no hover. Efeito de profundidade com perspectiva. Ideal para pricing cards, features, portfolio.",
        "intent": "card com spotlight, borda iluminada, hover premium, pricing card, feature card",
        "category": "data-display",
        "triggers": ["magic card", "spotlight", "borda iluminada", "card premium", "hover efeito", "pricing"],
        "mode": "landing", "edges": ["card"],
        "tokens": ["color", "spacing", "radius", "shadow", "animation"],
        "surfaces": ["S1", "S4", "S11", "S18"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-neon-gradient-card", "type": "molecule", "name": "Neon Gradient Card",
        "description": "Card com borda em efeito neon gradiente. Visual noturno, vibrante, tecnologia. Ideal para dashboards dark mode, landing tech, produtos digitais.",
        "intent": "card neon, borda gradiente, efeito neon, visual noturno, tech card, dashboard dark",
        "category": "data-display",
        "triggers": ["neon", "gradient", "borda neon", "card neon", "dark mode card", "tech"],
        "mode": "landing", "edges": ["card"],
        "tokens": ["color", "spacing", "radius", "shadow", "animation"],
        "surfaces": ["S1", "S3", "S11", "S18"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-shine-border", "type": "atom", "name": "Shine Border",
        "description": "Borda animada com efeito de brilho percorrendo o perimetro. Background border effect continuo. Aplicavel a cards, inputs, containers em foco.",
        "intent": "borda brilhante, shine border, perimetro animado, destaque de container, loading border",
        "category": "data-display",
        "triggers": ["shine border", "borda brilhante", "perimetro", "border animation", "container focus"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "radius", "animation"],
        "surfaces": ["S1", "S3", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "status", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },

    # ── Background Effects ──
    {
        "id": "magic-animated-grid-pattern", "type": "atom", "name": "Animated Grid Pattern",
        "description": "Background com padrao de grid animado feito com SVG. Totalmente customizavel via Tailwind CSS. Ideal para hero sections, backgrounds tecnicos.",
        "intent": "background grid animado, padrao SVG, hero background, fundo tecnico, grid pattern",
        "category": "layout",
        "triggers": ["grid pattern", "background grid", "svg pattern", "hero bg", "fundo grid", "tecnico"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S2", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-dot-pattern", "type": "atom", "name": "Dot Pattern",
        "description": "Background com padrao de pontos (dots) feito com SVG. Customizavel: cor, tamanho, espacamento. Ideal para fundos sutis, hero, secoes.",
        "intent": "background pontos, dot pattern, fundo sutil, hero background, dots SVG",
        "category": "layout",
        "triggers": ["dot pattern", "pontos", "dots", "fundo pontilhado", "svg dots", "background sutil"],
        "mode": "landing", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S2", "S11", "S20"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-grid-pattern", "type": "atom", "name": "Grid Pattern",
        "description": "Background grid estatico feito com SVG. Linhas horizontais e verticais. Customizavel via Tailwind CSS. Ideal para backgrounds tecnicos, dashboards.",
        "intent": "grid background, linhas, fundo quadriculado, svg grid, background dashboard",
        "category": "layout",
        "triggers": ["grid", "quadriculado", "linhas", "fundo grade", "background dashboard"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S3", "S20"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-retro-grid", "type": "atom", "name": "Retro Grid",
        "description": "Background grid com scroll animado estilo retro/synthwave. Efeito de perspectiva 3D com grade se movendo. Ideal para hero tech, landing futurista.",
        "intent": "retro grid, synthwave, perspectiva 3d, grid animado, hero futurista, fundo tech",
        "category": "layout",
        "triggers": ["retro", "synthwave", "perspectiva", "3d grid", "futurista", "neon grid"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-flickering-grid", "type": "atom", "name": "Flickering Grid",
        "description": "Grid que pisca sutilmente com efeito de flicker. Fundo animado organico. SVG customizavel. Ideal para atmosfera tech, cyberpunk.",
        "intent": "grid piscando, flicker, atmosfera tech, cyberpunk, fundo animado sutil",
        "category": "layout",
        "triggers": ["flicker", "piscando", "tech atmosphere", "cyberpunk", "grid animado"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-interactive-grid-pattern", "type": "atom", "name": "Interactive Grid Pattern",
        "description": "Grid que reage ao mouse. As linhas se movem em direcao ao cursor. Feito com SVG + interacao. Efeito de profundidade.",
        "intent": "grid interativo, mouse reactive, fundo que segue cursor, interactive background",
        "category": "layout",
        "triggers": ["interactive grid", "mouse grid", "grid que segue mouse", "fundo interativo"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-striped-pattern", "type": "atom", "name": "Striped Pattern",
        "description": "Background com padrao de listras feito com SVG. Angulo, cor, espessura customizaveis. Ideal para fundos com personalidade, secoes alternadas.",
        "intent": "background listrado, stripes, padrao listras, fundo com personalidade, svg stripes",
        "category": "layout",
        "triggers": ["stripes", "listras", "listrado", "background listras", "padrao diagonal"],
        "mode": "landing", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S2", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-hexagon-pattern", "type": "atom", "name": "Hexagon Pattern",
        "description": "Background com padrao de hexagonos em SVG. Visual geometrico moderno. Ideal para secoes tech, data, ciencia.",
        "intent": "background hexagono, geometrico, hexagon pattern, fundo tech, padrao hexagonal",
        "category": "layout",
        "triggers": ["hexagono", "hexagon", "geometrico", "fundo colmeia", "beehive"],
        "mode": "landing", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S20"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-noise-texture", "type": "atom", "name": "Noise Texture",
        "description": "Textura de ruido (noise) usando SVG feTurbulence. Camada de grain sutil sobreposta. Dessaturacao e contraste controlaveis. Ideal para dar textura organica.",
        "intent": "noise, ruido, textura, grain, organico, filme, camera, overlay sutil",
        "category": "layout",
        "triggers": ["noise", "ruido", "textura", "grain", "overlay", "organico", "filme"],
        "mode": "landing", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S11", "S19"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-warp-background", "type": "atom", "name": "Warp Background",
        "description": "Card com efeito de distorcao temporal no background. Time-warping visual. Ideal para headers, hero, secoes de destaque.",
        "intent": "warp, distorcao, time warp, background animado, efeito temporal, hero premium",
        "category": "layout",
        "triggers": ["warp background", "distorcao", "time warp", "fundo distorcido", "hero premium"],
        "mode": "landing", "edges": ["card"],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },

    # ── Beam/Light Effects ──
    {
        "id": "magic-animated-beam", "type": "atom", "name": "Animated Beam",
        "description": "Feixe de luz animado viajando por um caminho. Ideal para mostrar integracoes, fluxos, conexoes entre elementos.",
        "intent": "feixe de luz, beam, conexao visual, integracao, fluxo, linha animada, conexao",
        "category": "data-display",
        "triggers": ["beam", "feixe", "luz", "conexao", "integracao", "fluxo", "linha luz"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11", "S20"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-border-beam", "type": "atom", "name": "Border Beam",
        "description": "Feixe de luz animado percorrendo a borda de um container. Similar ao Shine Border mas com beam em vez de shimmer.",
        "intent": "beam na borda, borda iluminada, luz percorrendo borda, container com efeito",
        "category": "data-display",
        "triggers": ["border beam", "feixe na borda", "borda luz", "beam border"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "radius", "animation"],
        "surfaces": ["S1", "S3", "S4", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "status", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-light-rays", "type": "atom", "name": "Light Rays",
        "description": "Raios de luz animados descendo de cima. Efeito de luz divina/spotlight. Ideal para hero sections, headers dramaticos, elementos de destaque.",
        "intent": "raios de luz, light rays, luz divina, spotlight dramatico, hero effect",
        "category": "layout",
        "triggers": ["light rays", "raios de luz", "luz divina", "spotlight", "dramatico", "hero"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },

    # ── Animation Components ──
    {
        "id": "magic-marquee", "type": "molecule", "name": "Marquee",
        "description": "Faixa de rolagem infinita para texto, imagens ou videos. Horizontal ou vertical. Velocidade, direcao, pause-on-hover configuraveis. Ideal para logos de clientes, testimonials, noticias.",
        "intent": "carrossel infinito, marquee, scrolling infinito, logos de clientes, testimonials rotativos",
        "category": "data-display",
        "triggers": ["marquee", "carrossel", "scroll infinito", "logos", "testimonials", "faixa", "rolagem"],
        "mode": "landing", "edges": [],
        "tokens": ["animation", "spacing"],
        "surfaces": ["S1", "S2", "S11", "S13"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P0",
        "a11y_role": "marquee", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-confetti", "type": "atom", "name": "Confetti",
        "description": "Animacao de confetes. Dispara ao completar uma acao (compra, cadastro, milestone). Delight moment. Ideal para celebrar conquistas, welcome, upgrade.",
        "intent": "confete, celebracao, fogos, comemorar, delight, welcome, sucesso, milestone",
        "category": "feedback",
        "triggers": ["confetti", "confete", "celebracao", "fogos", "comemorar", "delight", "welcome"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "animation", "z-index"],
        "surfaces": ["S3", "S9", "S14"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-particles", "type": "atom", "name": "Particles",
        "description": "Particulas flutuantes no background. Sensacao de profundidade, movimento e interatividade. Ideal para hero, backgrounds vivos.",
        "intent": "particulas, particles, fundo com particulas, ambient, floating particles",
        "category": "layout",
        "triggers": ["particulas", "particles", "flutuantes", "ambient", "fundo vivo"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-meteors", "type": "atom", "name": "Meteors",
        "description": "Efeito de chuva de meteoros. Fogo cruzando a tela em diagonal. Visual espacial, dramatico. Ideal para hero sections de tecnologia, cripto, sci-fi.",
        "intent": "meteoros, meteors, estrelas cadentes, chuva de meteoros, efeito espacial",
        "category": "layout",
        "triggers": ["meteoros", "meteors", "estrelas cadentes", "chuva", "espacial", "sci-fi", "fogo"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-ripple", "type": "atom", "name": "Ripple",
        "description": "Efeito de ondulacao (ripple) atras de elementos. Ondas concentricas expandindo. Ideal para destacar secoes, elementos em foco.",
        "intent": "ripple, ondulacao, ondas, destaque de secao, efeito agua",
        "category": "layout",
        "triggers": ["ripple", "ondulacao", "ondas", "agua", "destaque", "concentrico"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-orbiting-circles", "type": "atom", "name": "Orbiting Circles",
        "description": "Circulos em orbita ao redor de um ponto central. Movimento circular continuo. Ideal para representar ecosistema, plataforma, conexoes.",
        "intent": "circulos orbitando, orbit, orbiting, ecosistema, plataforma, conexoes circulares",
        "category": "layout",
        "triggers": ["orbiting", "orbitas", "circulos", "ecosistema", "plataforma", "conexoes"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },

    # ── Layout Components ──
    {
        "id": "magic-bento-grid", "type": "organism", "name": "Bento Grid",
        "description": "Layout estilo Bento (Apple). Grid de cards de tamanhos variados. Organico e visualmente rico. Ideal para showcase de features, produtos, portfolio.",
        "intent": "bento grid, grid de features, layout bento, showcase produtos, portfolio visual",
        "category": "layout",
        "triggers": ["bento", "grid features", "showcase", "portfolio", "layout organico"],
        "mode": "landing", "edges": ["card"],
        "tokens": ["color", "spacing", "radius", "shadow"],
        "surfaces": ["S1", "S11", "S18"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P0",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-dock", "type": "organism", "name": "Dock",
        "description": "Implementacao do dock do MacOS. Menu de icones com zoom no hover. Animacao suave com motion. Ideal para navegacao inferior, toolbar de acoes.",
        "intent": "dock, macos dock, menu de icones, navegacao inferior, toolbar animada",
        "category": "navigation",
        "triggers": ["dock", "macos", "menu icones", "toolbar", "navegacao inferior", "icon bar"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "spacing", "radius", "animation", "shadow"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "navigation", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Interactive Components ──
    {
        "id": "magic-globe", "type": "molecule", "name": "Globe",
        "description": "Globo 3D interativo via WebGL. Autorotacao, drag, zoom. Altamente performatico. Ideal para mostrar presenca global, localizacoes, dados geo.",
        "intent": "globo 3d, mapa mundi, presenca global, localizacao, webgl globe, geo visualization",
        "category": "data-display",
        "triggers": ["globe", "globo", "mapa mundi", "3d", "webgl", "presenca global", "localizacao"],
        "mode": "landing", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "img", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-lens", "type": "atom", "name": "Lens",
        "description": "Efeito de lupa/zoom interativo. Ao passar mouse, amplia imagem ou video como uma lente. Ideal para preview de produto, zoom em imagem.",
        "intent": "lente, zoom, lupa, ampliar, magnificacao, preview produto, zoom imagem",
        "category": "data-display",
        "triggers": ["lens", "lente", "zoom", "lupa", "ampliar", "magnificar", "preview"],
        "mode": "landing", "edges": [],
        "tokens": ["animation"],
        "surfaces": ["S1", "S11", "S18"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "img", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-smooth-cursor", "type": "atom", "name": "Smooth Cursor",
        "description": "Cursor personalizado com fisica spring. Segue mouse com delay e amortecimento. Customizavel: cor, tamanho, efeito rotacao. Ideal para sites premium.",
        "intent": "cursor, mouse, pointer, smooth cursor, spring cursor, cursor premium",
        "category": "feedback",
        "triggers": ["cursor", "mouse", "pointer", "smooth", "spring", "fisica"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
    {
        "id": "magic-pointer", "type": "atom", "name": "Pointer",
        "description": "Componente que exibe um ponteiro (pointer) ao passar sobre elementos. Indicador visual de interatividade. Customizavel.",
        "intent": "ponteiro, pointer indicator, indicador de hover, elemento interativo",
        "category": "feedback",
        "triggers": ["pointer", "ponteiro", "indicador", "hover indicator"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },

    # ── Mockup Components ──
    {
        "id": "magic-safari", "type": "molecule", "name": "Safari Browser Mockup",
        "description": "Mockup do navegador Safari para mostrar websites. Barra de enderecos + botoes + conteudo. Ideal para showcases, portfolio, demonstracoes.",
        "intent": "browser mockup, safari, mostrar website, showcase, portfolio, demonstracao",
        "category": "data-display",
        "triggers": ["browser", "safari", "mockup", "showcase", "website preview", "navegador"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "radius", "shadow"],
        "surfaces": ["S1", "S11", "S18"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-iphone", "type": "molecule", "name": "iPhone Mockup",
        "description": "Mockup de iPhone para mostrar apps mobile. Tela + corpo do dispositivo. Ideal para preview de app, landing page de produto mobile.",
        "intent": "iphone mockup, celular, mobile preview, mostrar app, dispositivo, phone frame",
        "category": "data-display",
        "triggers": ["iphone", "celular", "mockup", "mobile", "app preview", "smartphone"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "radius", "shadow"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-android", "type": "molecule", "name": "Android Mockup",
        "description": "Mockup de dispositivo Android para mostrar apps. Similar ao iPhone mas com design Android. Ideal para preview multiplataforma.",
        "intent": "android mockup, celular android, mobile preview, multiplataforma, phone frame android",
        "category": "data-display",
        "triggers": ["android", "celular android", "mockup android", "phone frame"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "radius", "shadow"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-terminal", "type": "molecule", "name": "Terminal",
        "description": "Componente de terminal/console. Barra de titulo com botoes coloridos. Fundo escuro. Ideal para mostrar comandos, codigo, CLI.",
        "intent": "terminal, console, command line, cli, mostrar codigo, developer tool",
        "category": "data-display",
        "triggers": ["terminal", "console", "cli", "comando", "codigo", "shell", "bash"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "typography", "radius", "shadow"],
        "surfaces": ["S1", "S20"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-hero-video-dialog", "type": "organism", "name": "Hero Video Dialog",
        "description": "Video em modal no hero da pagina. Botao play → dialog com video. Thumbnail + overlay. Ideal para video de produto, demo, institucional.",
        "intent": "video hero, modal video, demo video, video produto, institucional, play button",
        "category": "data-display",
        "triggers": ["video", "hero video", "modal video", "demo", "play", "institucional"],
        "mode": "landing", "edges": ["dialog", "button"],
        "tokens": ["color", "radius", "shadow", "animation", "z-index"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "dialog", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Social/Media ──
    {
        "id": "magic-tweet-card", "type": "molecule", "name": "Tweet Card",
        "description": "Card que exibe um tweet com autor, handle, foto, texto e metricas. Ideal para social proof, testimonials embedados.",
        "intent": "tweet card, social proof, embed tweet, testimonial social, twitter card",
        "category": "data-display",
        "triggers": ["tweet", "twitter", "social proof", "testimonial", "embed", "social media"],
        "mode": "landing", "edges": ["card"],
        "tokens": ["color", "spacing", "radius", "shadow", "typography"],
        "surfaces": ["S1", "S2", "S7"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-code-comparison", "type": "molecule", "name": "Code Comparison",
        "description": "Componente que compara dois trechos de codigo lado a lado. Diff visual. Ideal para antes/depois, solucao/problema.",
        "intent": "comparacao de codigo, diff, antes depois, code diff, comparacao visual",
        "category": "data-display",
        "triggers": ["code comparison", "diff", "comparacao", "antes e depois", "codigo"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "typography", "spacing", "radius", "shadow"],
        "surfaces": ["S1", "S20"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "region", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-file-tree", "type": "molecule", "name": "File Tree",
        "description": "Arvore de diretorios e arquivos visual. Hierarquia com icones de pasta/arquivo. Ideal para documentacao, estrutura de projeto.",
        "intent": "arvore de arquivos, estrutura de projeto, diretorios, file tree, explorador",
        "category": "data-display",
        "triggers": ["file tree", "arvore", "diretorios", "estrutura", "pasta", "explorador"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "typography", "spacing"],
        "surfaces": ["S20", "S22"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "tree", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-icon-cloud", "type": "atom", "name": "Icon Cloud (3D Tag Cloud)",
        "description": "Nuvem 3D interativa de icones/tags. Rotaciona com mouse drag. Ideal para mostrar skills, tecnologias, categorias.",
        "intent": "nuvem de icones, tag cloud, skills cloud, tecnologias, categorias 3d",
        "category": "data-display",
        "triggers": ["icon cloud", "nuvem", "tag cloud", "skills", "tecnologias", "3d cloud"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "img", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },

    # ── Special Effects ──
    {
        "id": "magic-animated-circular-progress-bar", "type": "atom", "name": "Animated Circular Progress Bar",
        "description": "Barra de progresso circular animada. Gauge com valor percentual. SVG circle com stroke-dasharray animado. Ideal para KPI, metas, scoring.",
        "intent": "progresso circular, gauge, percentagem circular, meta visual, scoring circular",
        "category": "feedback",
        "triggers": ["circular progress", "gauge", "percentagem", "anel", "circular", "meta", "scoring"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S3", "S10", "S15"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P0",
        "a11y_role": "progressbar", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-scroll-progress", "type": "atom", "name": "Scroll Progress",
        "description": "Barra de progresso do scroll da pagina. Fixa no topo. Preenche conforme usuario rola. Ideal para artigos, landing pages longas.",
        "intent": "progresso de scroll, barra de leitura, scroll indicator, reading progress",
        "category": "feedback",
        "triggers": ["scroll progress", "barra de leitura", "progresso pagina", "scroll indicator"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S2", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "progressbar", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-scroll-based-velocity", "type": "molecule", "name": "Scroll Based Velocity",
        "description": "Texto cuja velocidade de scroll muda com base na velocidade do scroll do usuario. Efeito parallax avancado. Ideal para storytelling visual.",
        "intent": "scroll velocity, parallax, velocidade scroll, texto que reage ao scroll",
        "category": "data-display",
        "triggers": ["scroll velocity", "parallax", "velocidade", "scroll effect", "storytelling"],
        "mode": "landing", "edges": [],
        "tokens": ["animation", "typography"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-animated-list", "type": "molecule", "name": "Animated List",
        "description": "Lista onde cada item anima com delay sequencial. Stagger animation. Ideal para notificacoes, eventos, feed, timeline.",
        "intent": "lista animada, stagger animation, notificacoes, timeline, feed, entradas sequenciais",
        "category": "data-display",
        "triggers": ["animated list", "lista animada", "stagger", "notificacoes", "timeline", "feed"],
        "mode": "dashboard", "edges": [],
        "tokens": ["animation", "spacing"],
        "surfaces": ["S3", "S9", "S12", "S16"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "list", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-text-animate", "type": "atom", "name": "Text Animate",
        "description": "Animacao de texto com variedade de tipos: fade, slide, scale, blur. Config via props. Ideal para headlines, CTAs, elementos de destaque.",
        "intent": "texto animado, text animation, fade in, slide in, scale, entrada de texto",
        "category": "data-display",
        "triggers": ["text animate", "animacao texto", "fade in text", "slide text", "entrada texto"],
        "mode": "landing", "edges": [],
        "tokens": ["typography", "animation"],
        "surfaces": ["S1", "S2", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "text", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-animated-theme-toggler", "type": "molecule", "name": "Theme Toggler",
        "description": "Toggle de tema (light/dark) com animacao clip-path. Circulos, poligonos, estrela. View Transition API. Origem centrada no viewport.",
        "intent": "theme toggle, dark mode, light mode, modo escuro, alternar tema, animated toggle",
        "category": "action",
        "triggers": ["theme", "dark mode", "light mode", "toggle tema", "modo escuro", "view transition"],
        "mode": "design-system", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S3", "S9", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "switch", "a11y_keyboard": True, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-avatar-circles", "type": "molecule", "name": "Avatar Circles",
        "description": "Circulos de avatares sobrepostos. Overlap effect. Ideal para mostrar grupo, time, comunidade, 'X pessoas ja usam'.",
        "intent": "avatares sobrepostos, grupo de pessoas, time, social proof circulos, comunidade",
        "category": "data-display",
        "triggers": ["avatar group", "circulos", "sobreposicao", "time", "comunidade", "pessoas"],
        "mode": "dashboard", "edges": ["avatar"],
        "tokens": ["color", "spacing"],
        "surfaces": ["S1", "S3", "S9", "S19"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "group", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-progressive-blur", "type": "atom", "name": "Progressive Blur",
        "description": "Efeito de blur progressivo (gradiente de blur) em conteudo scrollavel. Indica que ha mais conteudo abaixo/acima. Ideal para scroll containers.",
        "intent": "blur progressivo, gradiente blur, indicador de scroll, mais conteudo, fade edges",
        "category": "feedback",
        "triggers": ["blur", "progressivo", "scroll hint", "fade edge", "mais conteudo", "overflow hint"],
        "mode": "dashboard", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S2", "S3", "S9"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-pixel-image", "type": "atom", "name": "Pixel Image",
        "description": "Imagem com efeito pixelado (retro aesthetic). Pixelation controlavel. Ideal para efeito nostalgia, jogos, estilo retro.",
        "intent": "imagem pixelada, pixel art, retro, nostalgia, efeito pixel, 8-bit",
        "category": "data-display",
        "triggers": ["pixel", "pixelado", "retro", "8-bit", "nostalgia", "pixel art"],
        "mode": "landing", "edges": [],
        "tokens": ["animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "img", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-dotted-map", "type": "atom", "name": "Dotted Map",
        "description": "Componente com mapa formado por pontos (dots). Visualizacao geografica estilizada. Ideal para mostrar cobertura, regioes, presenca.",
        "intent": "mapa pontilhado, dotted map, cobertura geografica, presenca, regioes, mapa estilizado",
        "category": "data-display",
        "triggers": ["dotted map", "mapa", "pontos", "cobertura", "geografico", "regioes"],
        "mode": "landing", "edges": [],
        "tokens": ["color"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P1",
        "a11y_role": "img", "a11y_keyboard": False, "a11y_contrast": 4.5,
    },
    {
        "id": "magic-glyph-matrix", "type": "atom", "name": "Glyph Matrix",
        "description": "Grid animado de glifos que mudam sutilmente. Fade effect + theme support. Ideal para background tech, dados, matrix.",
        "intent": "glyph matrix, glifos, matrix, background dados, caracteres, efeito hacker",
        "category": "layout",
        "triggers": ["glyph", "matrix", "glifos", "hacker", "dados", "caracteres"],
        "mode": "landing", "edges": [],
        "tokens": ["color", "animation"],
        "surfaces": ["S1", "S11"],
        "source_name": "21st-magic", "source_type": "component", "source_quality": "P2",
        "a11y_role": "presentation", "a11y_keyboard": False, "a11y_contrast": 3.0,
    },
]

# ═══════════════════════════════════════════════════════════════
# MERGE + DEDUP
# ═══════════════════════════════════════════════════════════════

ALL = SHADCN_CORE + MAGIC_VISUAL

def main():
    print(f"🧠 ADSENTICE · WARP M2 PREMIUM — Registry Semantico MAX")
    print(f"   Target: {COLLECTION} @ Qdrant :6352")
    print(f"   Components: {len(ALL)} total ({len(SHADCN_CORE)} shadcn/Radix + {len(MAGIC_VISUAL)} 21st-magic)")
    print()

    total = 0
    BATCH = 6

    for i in range(0, len(ALL), BATCH):
        batch = ALL[i:i + BATCH]
        embed_texts = [
            f"{c['description']} {c['intent']} {' '.join(c.get('triggers', [])[:10])}"[:800]
            for c in batch
        ]

        vecs = embed(embed_texts)
        points = [{"id": str(uuid.uuid4()), "vector": vec, "payload": mk_payload(c)}
                  for c, vec in zip(batch, vecs)]

        status = upsert(points)
        total += len(points)
        names = ", ".join(c["id"] for c in batch)
        print(f"  ✅ {len(points)}: {names} → {status}")

    # Verify
    tests = [
        ("botao de compra CTA principal premium", "button"),
        ("dashboard executivo metricas KPI", "card"),
        ("efeito visual premium landing page hero", "magic-animated-gradient-text"),
        ("confirmar exclusao modal alerta", "dialog"),
    ]
    print(f"\n🔍 VERIFY queries:")
    for query, expected in tests:
        vec = embed([query])[0]
        body = json.dumps({
            "vector": vec,
            "filter": {"must": [{"key": "kind", "match": {"value": "component"}}, {"key": "tag", "match": {"value": TAG}}]},
            "limit": 3,
            "with_payload": True,
        }).encode()
        req = Request(f"{QDRANT_URL}/collections/{COLLECTION}/points/search", data=body,
                      headers={"Content-Type": "application/json"}, method="POST")
        data = json.loads(urlopen(req, timeout=10).read())
        results = data.get("result", [])
        top = results[0]["payload"]["name"] if results else "N/A"
        match = "✅" if any(expected in r["payload"]["id"] for r in results[:3]) else "❌"
        print(f"   {match} '{query}' → {top}")

    print(f"\n🏁 {total} componentes Warp Premium registrados")
    print(f"   kind=component · tag={TAG}")
    print(f"   {len(SHADCN_CORE)} shadcn/Radix · {len(MAGIC_VISUAL)} 21st-magic")

if __name__ == "__main__":
    main()
